# Generated by Django 2.0.2 on 2018-03-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Reward's name")),
                ('url', models.URLField(verbose_name='Link to reward')),
            ],
        ),
    ]
