# Generated by Django 2.0.6 on 2018-06-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Link to reward'),
        ),
    ]
